#!/usr/bin/env bash
#
# This is the script that builds the project documentation into ../docs.
#
# If you are using MkDocs from Anaconda, you will need to have the right conda
# environment activated before you run this.

mkdocs build
rm -rf ../docs/*
cp -R _site/* ../docs

# Restore the CNAME that we blew away earlier, or we'll lose our custom GitHub
# Pages domain name

cp ../.github/CNAME ../docs
